services:
  - name: django
    envVars:
      - key: DJANGO_SECRET_KEY
        from: secret
      - key: DEBUG
        value: "false"
    healthCheckPath: "/"

env:
  - name: RENDER_ENVIRONMENT_NAME
    value: "django"  