name: CI/CD with Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: dakshayini08v
          password: Welcome@123

      - name: Build and push Docker image
        run: |
          docker build -t django-ci-cd .
          docker tag django-ci-cd dakshayini08v/django-ci-cd-implementation:latest
          docker push dakshayini08v/django-ci-cd-implementation:latest
       
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade setuptools
        run: python -m pip install --upgrade setuptools
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOCKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.RENDER_API_KEY }}
          base: main  # Replace with Render's connected branch
          branch: deploy-from-actions
          title: Deploy from GitHub Actions
          body: Automated deployment from GitHub Actions

      - name: Monitor deployment status (optional)
        run: |
          # Use Render's API or CLI to monitor deployment progress and status